#!groovy

// Generated by IBM TransformationAdvisor
// Mon Mar 04 16:26:20 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}