#!groovy

// Generated by IBM TransformationAdvisor
// Fri Jan 04 16:37:29 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}