#!groovy

// Generated by IBM TransformationAdvisor
// Fri Feb 01 20:23:23 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'pbwear'
    mvnCommands = '--version'
    test='false'
}